node_to_func = {
    "eq": "op_eq(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "gt": "op_gt(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "lt": "op_lt(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "gte": "op_gte(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "lte": "op_lte(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "neq": "op_neq(series1: pd.Series, series2_or_literal: Union[pd.Series, int, float, str]) -> pd.Series",
    "is": "op_is_null(series: pd.Series) -> pd.Series|op_is_not_null(series: pd.Series) -> pd.Series",
    "null": "op_is_null(series: pd.Series) -> pd.Series",
    "in": "op_in(series: pd.Series, values: list) -> pd.Series",
    "between": "op_between(series: pd.Series, min_val: Any, max_val: Any) -> pd.Series",
    "like": "op_like(series: pd.Series, pattern: str) -> pd.Series",
    "not": "op_not(condition: pd.Series) -> pd.Series",
    "add": "op_add(series1: Union[pd.Series, int, float, np.number], series2_or_literal: Union[pd.Series, int, float, np.number]) -> Union[pd.Series, int, float, np.number]",
    "sub": "op_sub(series1: Union[pd.Series, int, float, np.number], series2_or_literal: Union[pd.Series, int, float, np.number]) -> Union[pd.Series, int, float, np.number]",
    "mul": "op_mul(series1: Union[pd.Series, int, float, np.number], series2_or_literal: Union[pd.Series, int, float, np.number]) -> Union[pd.Series, int, float, np.number]",
    "div": "op_null_if(expr1: pd.Series, expr2: Union[Any, pd.Series]) -> pd.Series|op_div(series1: Union[pd.Series, int, float, np.number], series2_or_literal: Union[pd.Series, int, float, np.number]) -> Union[pd.Series, int, float]",
    "neg": "op_neg(series: Union[pd.Series, int, float, np.number]) -> Union[pd.Series, int, float, np.number]",
    "and": "op_and(*conditions: pd.Series) -> pd.Series",
    "or": "op_or(*conditions: pd.Series) -> pd.Series",
    "count": "op_count(obj: Union[pd.Series, pd.DataFrame, pd.core.groupby.SeriesGroupBy, pd.Index]) -> Union[int, pd.Series]",
    "sum": "op_sum(grouped: pd.core.groupby.SeriesGroupBy) -> pd.Series",
    "avg": "op_avg(grouped: pd.core.groupby.SeriesGroupBy) -> pd.Series",
    "max": "op_max(grouped: pd.core.groupby.SeriesGroupBy) -> pd.Series",
    "min": "op_min(grouped: pd.core.groupby.SeriesGroupBy) -> pd.Series",
    "groupconcat": "op_group_concat(col: str, df: Union[pd.DataFrame, pd.core.groupby.DataFrameGroupBy], separator: str = ',', distinct: bool = False, order_by: Optional[str] = None) -> Union[pd.Series, str]",
    "substring": "op_substring(series: pd.Series, start: Union[int, pd.Series], length: Optional[Union[int, pd.Series]] = None) -> pd.Series",
    "length": "op_length(series: pd.Series) -> pd.Series",
    "trim": "op_trim(series: pd.Series, chars: Optional[str] = None) -> pd.Series",
    "lower": "op_lower(series: pd.Series) -> pd.Series",
    "round": "op_round(series: pd.Series, decimals: int = 0) -> pd.Series",
    "cast": "op_cast(series: pd.Series, target_type: str) -> pd.Series",
    "timestampdiff": "op_timestamp_diff(unit: str, start_series: pd.Series, end_series: pd.Series) -> pd.Series",
    "datediff": "op_date_diff(unit: str, start_series: pd.Series, end_series: pd.Series, as_integer: bool = True) -> pd.Series",
    "strposition": "op_strposition(substr: str, series: pd.Series) -> pd.Series",
    "abs": "op_abs(series: pd.Series) -> pd.Series",
    "timetostr": "op_timetostr(datetime_input: Union[pd.Series, pd.Timestamp, datetime.date], format_string: str) -> pd.Series",
    "tsordstotimestamp": "op_to_datetime(date_input: Union[str, pd.Series], errors: str = 'coerce') -> pd.Series",
    "date": "op_date(series: pd.Series) -> pd.Series",
    "currenttimestamp": "op_current_timestamp() -> pd.Timestamp",
    "group": "build_group_by(df: pd.DataFrame, *columns: str) -> pd.core.groupby.DataFrameGroupBy",
    "order": "build_order_by(df: pd.DataFrame, *columns_with_direction: Union[Tuple[str, str], str]) -> pd.DataFrame",
    "limit": "build_limit(df: pd.DataFrame, count: int, offset: int = 0) -> pd.DataFrame",
    "offset": "build_limit(df: pd.DataFrame, count: int, offset: int = 0) -> pd.DataFrame",
    "join": "build_join(df1: pd.DataFrame, df2: pd.DataFrame, join_type: str = 'inner', left_on: Optional[Union[str, List[str]]] = None, right_on: Optional[Union[str, List[str]]] = None, suffix_for_overlap_cols: Tuple[str, str] = ('_x', '_y')) -> pd.DataFrame",
    "union": "op_union(df1: pd.DataFrame, df2: pd.DataFrame, keep_duplicates: bool = False) -> pd.DataFrame",
    "except": "op_except(df1: pd.DataFrame, df2: pd.DataFrame) -> pd.DataFrame",
    "distinct": "op_distinct(df: pd.DataFrame, columns: Optional[List[str]] = None) -> pd.DataFrame",
    "datatype": "op_cast(series: pd.Series, target_type: str) -> pd.Series",
    "rownumber": "op_row_number(df: pd.DataFrame, partition_by_cols: Optional[List[str]] = None, order_by_cols_with_direction: Optional[List[str]] = None) -> pd.Series",
    "if": "op_if(condition: pd.Series, true_value: Union[Any, pd.Series], false_value: Union[Any, pd.Series], index_source: pd.Index) -> pd.Series",
    "case": "op_case(*when_then_pairs: Tuple[pd.Series, Union[Any, pd.Series]], else_value: Optional[Union[Any, pd.Series]] = None, index_source: Optional[pd.Index] = None) -> pd.Series",
    "RANK": "op_rank(df: pd.DataFrame, partition_by_cols: Optional[List[str]] = None, order_by_cols_with_direction: Optional[List[str]] = None) -> pd.Series",
    "DENSE_RANK": "op_dense_rank(df: pd.DataFrame, partition_by_cols: Optional[List[str]] = None, order_by_cols_with_direction: Optional[List[str]] = None) -> pd.Series",
    "REPLACE": "op_replace(series: pd.Series, old_str: str, new_str: str) -> pd.Series",
    "JULIANDAY": "op_julianday(series: Union[pd.Series, pd.Timestamp, datetime.date]) -> pd.Series",
    "TIME": "op_time_extract(time_input: Union[str, pd.Timestamp, pd.Series]) -> Union[datetime.time, pd.Series]",
    "NOW": "op_current_timestamp() -> pd.Timestamp",
    "TOTAL": "op_sum(grouped: pd.core.groupby.SeriesGroupBy) -> pd.Series",
    "dpipe": "op_concat(*args: pd.Series, handle_nulls_strictly: bool = False) -> pd.Series",
    "DATETIME": "op_to_datetime(date_input: Union[str, pd.Series], errors: str = 'coerce') -> pd.Series",
    "exists": "op_isin(series1: pd.Series, series2: pd.Series) -> pd.Series",
}
