node_to_func = {
    # 基本操作符
    'eq': 'op_eq(col1, col2_or_literal, df=None)',
    'gt': 'op_gt(col1, col2_or_literal, df=None)',
    'lt': 'op_lt(col1, col2_or_literal, df=None)',
    'gte': 'op_gte(col1, col2_or_literal, df=None)',
    'lte': 'op_lte(col1, col2_or_literal, df=None)',
    'neq': 'op_neq(col1, col2_or_literal, df=None)',
    'is': 'op_is_null(col1, df=None)',
    'null': 'op_is_null(col1, df=None)',
    'in': 'op_in(col1, values, df=None)',
    'between': 'op_between(col1, min_val, max_val, df=None)',
    'like': 'op_like(col1, pattern, df=None)',
    'not': 'op_not(condition, df=None)',
    'add': 'op_add(col1, col2, df=None)',
    'sub': 'op_sub(col1, col2, df=None)',
    'mul': 'op_mul(col1, col2, df=None)',
    'div': 'op_div(col1, col2, df=None)',
    'neg': 'op_neg(col1, df=None)',
    'and': 'op_and(*conditions, df=None)',
    'or': 'op_or(*conditions, df=None)',
    # 聚合/函数
    'count': 'op_count(col="*", distinct=False, df=None)',
    'sum': 'op_sum(col, distinct=False, df=None)',
    'avg': 'op_avg(col, distinct=False, df=None)',
    'max': 'op_max(col, df=None)',
    'min': 'op_min(col, df=None)',
    'groupconcat': 'op_group_concat(col, separator=",", distinct=False, order_by=None, df=None)',
    'substring': 'op_substring(col, start, length=None, df=None)',
    'length': 'op_length(col, df=None)',
    'trim': 'op_trim(col, df=None)',
    'lower': 'op_lower(col, df=None)',
    'round': 'op_round(col, decimals=0, df=None)',
    'cast': 'op_cast(col, target_type, df=None)',
    'timestampdiff': 'op_timestamp_diff(unit, start_expression, end_expression, df=None)',
    'datediff': 'op_date_diff(unit, start_expression, end_expression, df=None)',
    'strposition': 'op_strposition(substr, col, df=None)',
    'abs': 'op_abs(col, df=None)',
    'timetostr': 'op_timetostr(expression, format_string, df=None)',
    'tsordstotimestamp': 'op_to_datetime(expression, df=None)',
    # 时间/类型相关
    'date': 'op_date(func_name, *args, df=None)',
    'currenttimestamp': 'op_current_timestamp(df=None)',
    # 结构性节点（用构建器函数）
    'select': None,
    'from': None,
    'group': 'build_group_by(*columns, df=None)',
    'order': 'build_order_by()',
    'limit': 'build_limit(count, offset=None, df=None)',
    'offset': 'build_limit(count, offset, df=None)',
    'join': 'build_join(table_name, join_type=\"inner\", df1=None, df2=None, left_on=None, right_on=None)',
    'INNER JOIN': 'build_join(table_name, join_type=\"inner\", df1=None, df2=None, left_on=None, right_on=None)',
    'union': 'op_union(sql1, sql2, all=False, df1=None, df2=None)',
    'except': 'op_except(sql1, sql2, df1=None, df2=None)',
    # 结构性/特殊节点（无需单独op_函数，调度时特殊处理）
    'subquery': None,  # 递归还原
    'star': None,      # SELECT * 由build_select支持
    'distinct': 'op_distinct(df, columns=None)', # 由build_select的distinct参数支持
    'alias': None,
    'table': None,     # 由from子句支持
    'tablealias': None,
    'datatype': 'op_cast(col, target_type, df=None)',
    'rownumber': 'op_row_number(partition_by_cols=None, order_by_cols_with_direction=None, df=None)',
    # 在stat_atomic_operators.py中添加：
'if': 'op_if(condition, true_value, false_value, df=None)',
'case': 'op_case(*when_then_pairs, else_value=None, df=None)',
'RANK': 'op_rank(partition_by_cols=None, order_by_cols_with_direction=None, df=None)',
'DENSE_RANK': 'op_dense_rank(partition_by_cols=None, order_by_cols_with_direction=None, df=None)',
'REPLACE': 'op_replace(col, old_str, new_str, df=None)',
'JULIANDAY': 'op_julianday(col, df=None)',
'TIME': 'op_time_extract(time_str, df=None)',
'NOW': 'op_current_timestamp(df=None)',
'TOTAL': 'op_sum(col, distinct=False, df=None)',
'identifier': None,
'column': None,
'literal': None,
'where': None,
'ordered': None,
'paren': None,
'having': None,
'anonymous': None,
'cte': None,
'window': None,
'with': None,
'dpipe': 'op_concat(*args, df=None)',
'DATETIME': 'op_to_datetime(func_name, *args, df=None)',
'var': None,
'exists': 'op_isin(col1, col2, df1=None, df2=None)',
'boolean': None,

}